### PR TITLE
Change colors

### PR DESCRIPTION
**Pull request by ys**
Light background
dark font
some overlay for readability
links ids

### CODE REVIEW

**Comment by hannesfostie** [comment]
I like this a lot. Did you ever consider a career in webdesign? Maybe becoming a true unicorn?

edit: don't mind the sarcasm, I really do like this :-)

**Comment by ys** [comment]
LULZ I just changed two colors and added an overlay:D

**Comment by joren** [comment]
:+1:

**Comment by kvzb** [comment]
@ys while watching yoga videos apparently. Seriously though I like it a lot like that. :shipit:

**Comment by ys** [comment]
I am happy I didn't leaked stuff:D

**Comment by toch** [comment]
I also lighten the map. works better with the light colors.

Super thanks @ys :+1:

**Pull request merged**
